theme: jekyll-theme-minimal

title: Giovanni Omeri 
description: Graduating in Ux Design at the Milano-Bicocca University.
I deal with accessibility, usability, inclusiveness, acceptability and sustainability.
